### ISSUE TITLE
コードについて

### ISSUE THREAD

**Issue by c0b21035** [c0b2111568/ProjExD#9]
https://github.com/c0b2111568/ProjExD/blob/04129cce1924220cfb8243e3cf39d172f69ef7ba/ex03/maze.py#L43
ここの画像を表示するコード簡単にできると思うので直した方がいいと思います

**Comment by c0b2111568** [comment]
今回は矢印が押されたときに画像を変更する仕様になっているのでまとめなくてもいいと思いました
